package service

import (
	"fmt"
	"strings"
)

// GenerateWorkerCode produces a Cloudflare Worker JS script that uses the
// supplied clean IPs as the backend address list.  The template is ported
// from GetWorkerCode.ts.
func GenerateWorkerCode(cleanIPs []IPResult) string {
	if len(cleanIPs) == 0 {
		return "// No clean IPs found yet – run a scan first."
	}

	// Sample up to 100 IPs weighted by latency for the worker array
	sampled := SampleIPsWeighted(cleanIPs, 100)
	if len(sampled) == 0 {
		sampled = make([]string, len(cleanIPs))
		for i, r := range cleanIPs {
			sampled[i] = r.IP
		}
	}

	// Build the JS array literal
	quotedIPs := make([]string, len(sampled))
	for i, ip := range sampled {
		quotedIPs[i] = fmt.Sprintf("'%s'", ip)
	}
	allowedIpsStr := strings.Join(quotedIPs, ",\n\t\t")

	return fmt.Sprintf(`// Version 1.0.3 – generated by V2ray-Cloudflare GUI

const maxConfigItems = 500
const maxPerType = 200
const includeOriginalConfigs = false

const subLinks = [
    "https://raw.githubusercontent.com/freefq/free/master/v2",
    "https://raw.githubusercontent.com/Pawdroid/Free-servers/main/sub",
    "https://raw.githubusercontent.com/aiboboxx/v2rayfree/main/v2",
    "https://raw.githubusercontent.com/AzadNetCH/Clash/main/V2Ray.txt"
]
const cnfLinks = [
    "https://raw.githubusercontent.com/mahdibland/ShadowsocksAggregator/master/sub/sub_merge.txt",
    "https://raw.githubusercontent.com/awesome-vpn/awesome-vpn/master/all"
]

const addressList = ["discord.com", "cloudflare.com", "nginx.com", "cdnjs.com", "vimeo.com", "networksolutions.com", "spotify.com"]
const fpList = ["chrome", "chrome", "chrome", "firefox", "safari", "edge", "ios", "android", "random", "random"]
const alpnList = ["http/1.1", "h2,http/1.1", "h2,http/1.1"]
var cleanIPs = [%s]

export default {
    async fetch(request) {
    var url = new URL(request.url)
    var pathParts = url.pathname.replace(/^\/|\/$/g, "").split("/")
    var type = pathParts[0].toLowerCase()
    if (["sub", "clash"].includes(type)) {

        var configList = []
        for (var subLink of subLinks) {
        try {
            configList = configList.concat(await fetch(subLink).then(r => r.text()).then(a => atob(a)).then(t => t.split("\n")))
        } catch (e) { }
        }
        for (var cnfLink of cnfLinks) {
        try {
            configList = configList.concat(await fetch(cnfLink).then(r => r.text()).then(t => t.split("\n")))
        } catch (e) { }
        }

        var vmessConfigList = configList.filter(cnf => (cnf.search("vmess://") == 0))
        var trojanConfigList = configList.filter(cnf => (cnf.search("trojan://") == 0))
        var ssConfigList = configList.filter(cnf => (cnf.search("ss://") == 0))
        var mergedConfigList = []

        if (type == "sub") {
        if (includeOriginalConfigs) {
            mergedConfigList = mergedConfigList.concat(getMultipleRandomElements(vmessConfigList, maxPerType))
        }
        mergedConfigList = mergedConfigList.concat(
            getMultipleRandomElements(
            vmessConfigList.map(decodeVmess).map(cnf => mixConfig(cnf, url, "vmess")).filter(cnf => (!!cnf && cnf.id)).map(encodeVmess).filter(cnf => !!cnf),
            maxPerType
            )
        )
        return new Response(btoa(getMultipleRandomElements(mergedConfigList, maxConfigItems).join("\n")));
        } else { // clash
        mergedConfigList = mergedConfigList.concat(
            getMultipleRandomElements(
            vmessConfigList.map(decodeVmess).map(cnf => mixConfig(cnf, url, "vmess")).filter(cnf => (cnf && cnf.id)).map(cnf => toClash(cnf, "vmess")),
            maxPerType
            )
        )
        return new Response(toYaml(mergedConfigList));
        }
    } else {
        var newUrl = new URL("https://" + url.pathname.replace(/^\/|\/$/g, ""))
        return fetch(new Request(newUrl, request));
    }
    }
}

function encodeVmess(conf) {
    try { return "vmess://" + btoa(JSON.stringify(conf)) } catch { return null }
}

function decodeVmess(conf) {
    try { return JSON.parse(atob(conf.substr(8))) } catch { return {} }
}

function mixConfig(conf, url, protocol) {
    try {
    if (conf.tls != "tls") { return {} }
    var addr = conf.sni
    if (!addr) {
        if (conf.add && !isIp(conf.add)) addr = conf.add
        else if (conf.host && !isIp(conf.host)) addr = conf.host
    }
    if (!addr) { return conf }
    conf.name = (conf.name ? conf.name : conf.ps) + '-Worker'
    conf.sni = url.hostname
    if (cleanIPs.length) {
        conf.add = cleanIPs[Math.floor(Math.random() * cleanIPs.length)]
    } else {
        conf.add = addressList[Math.floor(Math.random() * addressList.length)]
    }
    if (protocol == "vmess") {
        conf.sni = url.hostname
        conf.host = url.hostname
        if (conf.path == undefined) conf.path = ""
        conf.path = "/" + addr + ":" + conf.port + "/" + conf.path.replace(/^\//g, "")
        conf.fp = fpList[Math.floor(Math.random() * fpList.length)]
        conf.alpn = alpnList[Math.floor(Math.random() * alpnList.length)]
        conf.port = 443
    }
    return conf
    } catch (e) { return {} }
}

function getMultipleRandomElements(arr, num) {
    return arr.slice(0, num)
}

function isIp(str) {
    try {
    if (!str) return false
    return /^(\d{1,3}\.){3}\d{1,3}$/.test(str)
    } catch (e) { return false }
}

function toClash(conf, protocol) {
    try {
    var config = {
        name: (conf.name ? conf.name : conf.ps),
        type: protocol,
        server: conf.add,
        port: conf.port,
        uuid: conf.id,
        alterId: 0,
        tls: true,
        cipher: conf.cipher ? conf.cipher : "auto",
        "skip-cert-verify": true,
        servername: conf.sni,
        network: conf.net,
        "ws-opts": { path: conf.path, headers: { host: conf.host } }
    }
    config.name = config.name.replace(/[^\x20-\x7E]/g, "").replace(/[\s\/:|@\(\)\.]/g, "") + "-" + Math.floor(Math.random() * 10000)
    return config
    } catch (e) { return {} }
}

function toYaml(configList) {
    return `+"`"+`
mixed-port: 7890
allow-lan: true
log-level: info
external-controller: 0.0.0.0:9090
dns:
  enabled: true
  nameserver:
    - 1.1.1.1
    - 4.2.2.4
  fallback:
    - 8.8.8.8
    - 8.8.4.4

proxies:
`+"${configList.map(cnf => \"  - \" + JSON.stringify(cnf)).join(\"\\n\")}"+`

proxy-groups:
  - name: maingroup
    type: url-test
    tolerance: 300
    url: 'https://www.google.com/generate_204'
    interval: 30
    lazy: false
    proxies:
`+"${configList.map(cnf => \"      - \" + cnf.name.trim()).join(\"\\n\")}"+`

rules:
  - GEOIP,IR,DIRECT
  - MATCH,maingroup
`+"`"+`
}`, allowedIpsStr)
}
